<a href="https://colab.research.google.com/github/malh718/datasci_1_loading/blob/main/HHA507HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HHA 507 HW 1

## HIV related CSV file examples

In [ ]:
import pandas as pd

In [71]:
HIVny = pd.read_csv('HIVNY.csv')

In [72]:
HIVny

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
0,2011,All,All,All,All,All,3379,48.3,640,66,2366,33.8,1.1,71,2040,13.6,5.8,7.8
1,2011,All,All,Male,All,All,2595,79.1,480,66,1712,52.2,1.7,72,1423,13.4,5.7,7.7
2,2011,All,All,Female,All,All,733,21.1,153,66,622,17.6,0.6,68,605,14.0,6.0,8.0
3,2011,All,All,Transgender,All,All,51,99999.0,7,63,32,99999.0,99999.0,55,12,11.1,5.7,5.4
4,2011,All,All,Female,13 - 19,All,47,13.6,4,64,22,6.4,0.1,57,1,1.4,1.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000,2015,Staten Island,Willowbrook,Male,All,Asian/Pacific Islander,0,0.0,0,99999,0,0.0,0.1,100,0,0.0,99999.0,99999.0
6001,2015,Staten Island,Willowbrook,Male,All,Black,1,72.4,0,100,0,0.0,1.1,80,0,0.0,99999.0,99999.0
6002,2015,Staten Island,Willowbrook,Male,All,Latino/Hispanic,2,43.9,0,100,0,0.0,0.7,87,1,8.3,99999.0,99999.0
6003,2015,Staten Island,Willowbrook,Male,All,Other/Unknown,1,218.9,0,0,0,0.0,0.7,100,0,0.0,99999.0,99999.0
6004,2015,Staten Island,Willowbrook,Male,All,White,0,0.0,0,99999,0,0.0,0.2,93,0,0.0,99999.0,99999.0

In [75]:
HIVny.columns

Index(['Year', 'Borough', 'UHF', 'Gender', 'Age', 'Race', 'HIV diagnoses',
       'HIV diagnosis rate', 'Concurrent diagnoses',
       '% linked to care within 3 months', 'AIDS diagnoses',
       'AIDS diagnosis rate', 'PLWDHI prevalence', '% viral suppression',
       'Deaths', 'Death rate', 'HIV-related death rate',
       'Non-HIV-related death rate'],
      dtype='object')

In [ ]:
HIVincidence = pd.read_csv('HIVIncidence Rate2009-2021.csv')

In [ ]:
HIVincidence

,Jurisdiction,Value,Race/ ethnicity,Year,Measure
0,Caroline,NaN,Asian,2017,HIV Incidence
1,State,20.4,All races/ ethnicities (aggregated),2017,HIV Incidence
2,Allegany,6.4,All races/ ethnicities (aggregated),2017,HIV Incidence
3,Anne Arundel,8.7,All races/ ethnicities (aggregated),2017,HIV Incidence
4,Baltimore City,44.7,All races/ ethnicities (aggregated),2017,HIV Incidence
...,...,...,...,...,...
1520,State,3.4,White Non-Hispanic/Latino,2021,HIV Incidence
1521,Allegany,2.0,White Non-Hispanic/Latino,2021,HIV Incidence
1522,Anne Arundel,3.0,White Non-Hispanic/Latino,2021,HIV Incidence
1523,Baltimore City,6.3,White Non-Hispanic/Latino,2021,HIV Incidence
1524,Baltimore County,4.2,White Non-Hispanic/Latino,2021,HIV Incidence

In [76]:
HIVincidence.columns

Index(['Jurisdiction', 'Value', 'Race/ ethnicity', 'Year', 'Measure'], dtype='object')

In [ ]:
STItest = pd.read_csv('STItest.csv')

In [ ]:
STItest

,Fiscal Years (FY),STI Test Type,Number of STI Tests Provided,Percentage of STI Tests Provided,Annotation Code,Annotation Description
0,2003,Chlamydia,"958,622",35%,NaN,NaN
1,2003,Genital Herpes,"4,965",0.18%,NaN,NaN
2,2003,Gonorrhea,"977,345",35%,NaN,NaN
3,2003,HIV,"404,956",14.65%,NaN,NaN
4,2003,Human Papillomavirus (HPV),"25,453",0.92%,NaN,NaN
...,...,...,...,...,...,...
121,2020,Gonorrhea,"234,606",29%,NaN,NaN
122,2020,HIV,"84,660",11%,NaN,NaN
123,2020,Human Papillomavirus (HPV),0,0%,NaN,NaN
124,2020,Syphilis,"103,287",13%,NaN,NaN
125,2020,Other,"11,497",1%,NaN,NaN

In [77]:
STItest.columns

Index(['Fiscal Years (FY)', 'STI Test Type ', 'Number of STI Tests Provided',
       'Percentage of STI Tests Provided', 'Annotation Code',
       'Annotation Description'],
      dtype='object')

## Diabetes related XLSX file examples

In [ ]:
import pandas as pd

In [ ]:
diaindia = pd.read_excel('Diabetes.xlsx')

In [ ]:
diaindia

,States/UTs,Area,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Men age 15-49 years who are anaemic (<13.0 g/dl)22 (%),Men age 15-19 years who are anaemic (<13.0 g/dl)22 (%),Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%),Men (age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)
0,India,Urban,160138,179535,26420,20.39,25.04,,7.97,16.27,7.81,8.54,17.85
1,India,Rural,476561,544580,75419,27.41,33.86,5.87,5.47,12.27,7.02,6.49,14.51
2,India,Total,636699,724115,101839,25.04,31.13,6.12,6.25,13.51,7.27,7.15,15.58
3,Andaman & Nicobar Islands,Urban,527,557,85,9.18,*,8.59,9.39,19.64,9.49,8.56,19.44
4,Andaman & Nicobar Islands,Rural,2097,1840,282,20.36,-25.59,6.7,7.32,16.19,9.12,6.55,17.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,Uttarakhand,Rural,9811,10694,1270,15.58,26.33,4.09,4.83,9.56,5.73,6.63,13.34
107,Uttarakhand,Total,12169,13280,1586,15.14,27.64,4.19,5.63,10.84,5.64,7.55,14.25
108,West Bengal,Urban,5442,6358,942,30.94,27.64,9.68,8.61,19.44,11.19,10.64,23.11
109,West Bengal,Rural,12745,15050,2079,42.42,42.83,8.53,7.22,16.53,10.56,8.99,20.40
110,West Bengal,Total,18187,21408,3021,38.85,38.71,8.91,7.68,17.49,10.77,9.54,21.31

In [78]:
diaindia.columns

Index(['States/UTs', 'Area', 'Number of Households surveyed',
       'Number of Women age 15-49 years interviewed',
       'Number of Men age 15-54 years interviewed',
       'Men age 15-49 years who are anaemic (<13.0 g/dl)22 (%)',
       'Men age 15-19 years who are anaemic (<13.0 g/dl)22 (%)',
       'Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)',
       'Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)',
       'Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)',
       'Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)',
       'Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)',
       'Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)'],
      dtype='object')

In [43]:
gestationaldiabetes = pd.read_excel('Gestdia.xlsx')

In [44]:
gestationaldiabetes

,Case Number,Age,No of Pregnancy,Gestation in previous Pregnancy,BMI,HDL,Family History,unexplained prenetal loss,Large Child or Birth Default,PCOS,Sys BP,Dia BP,OGTT,Hemoglobin,Sedentary Lifestyle,Prediabetes,Class Label(GDM /Non GDM)
0,1,22,2,1,NaN,55.0,0,0,0,0,102.0,69,NaN,12.0,0,0,0
1,2,26,2,1,NaN,53.0,0,0,0,0,101.0,63,NaN,12.4,0,0,0
2,3,29,1,0,NaN,50.0,0,0,0,0,118.0,79,NaN,14.3,0,0,0
3,4,28,2,1,NaN,51.0,0,0,0,0,99.0,70,NaN,15.0,0,0,0
4,5,21,2,1,NaN,52.0,0,0,0,0,116.0,65,NaN,15.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,3521,31,4,1,24.1,32.0,0,0,1,0,150.0,107,187.0,13.4,1,1,1
3521,3522,26,3,1,34.5,43.0,1,1,0,1,166.0,85,164.0,14.2,0,0,1
3522,3523,35,2,2,23.6,56.0,1,0,1,0,178.0,81,141.0,15.3,0,1,1
3523,3524,37,2,0,23.3,28.0,1,0,1,1,139.0,115,133.0,13.3,0,1,0
3524,3525,43,2,0,28.6,30.0,1,1,0,0,121.0,63,179.0,15.8,1,0,0

In [79]:
gestationaldiabetes.columns

Index(['Case Number', 'Age', 'No of Pregnancy',
       'Gestation in previous Pregnancy', 'BMI', 'HDL', 'Family History',
       'unexplained prenetal loss', 'Large Child or Birth Default', 'PCOS',
       'Sys BP', 'Dia BP', 'OGTT', 'Hemoglobin', 'Sedentary Lifestyle',
       'Prediabetes', 'Class Label(GDM /Non GDM)'],
      dtype='object')

In [45]:
diabetespregstats = pd.read_excel('diapregstats.xlsx')

In [46]:
diabetespregstats

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [80]:
diabetespregstats.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

## Cancer and COVID related JSON file examples

In [ ]:
import pandas as pd

In [47]:
cervcanc = pd.read_json('cerv_cancer.json')

In [48]:
cervcanc

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs,Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4,15,1,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
1,15,1,14,1,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
2,34,1,?,1,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
3,52,5,16,4,1,37,{'year)': '37'},1,3,0,...,?,?,1,0,1,0,0,0,0,0
4,46,3,21,4,0,0,{'year)': '0'},1,15,0,...,?,?,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,34,3,18,0,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
964,32,2,19,1,0,0,{'year)': '0'},1,8,0,...,?,?,0,0,0,0,0,0,0,0
965,25,2,17,0,0,0,{'year)': '0'},1,0.08,0,...,?,?,0,0,0,0,0,0,1,0
966,33,2,24,2,0,0,{'year)': '0'},1,0.08,0,...,?,?,0,0,0,0,0,0,0,0
967,29,2,20,1,0,0,{'year)': '0'},1,0.5,0,...,?,?,0,0,0,0,0,0,0,0

In [81]:
cervcanc.columns

Index(['Age', 'Number of sexual partners', 'First sexual intercourse',
       'Num of pregnancies', 'Smokes', 'Smokes (years)', 'Smokes (packs',
       'Hormonal Contraceptives', 'Hormonal Contraceptives (years)', 'IUD',
       'IUD (years)', 'STDs', 'STDs (number)', 'STDs:condylomatosis',
       'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis',
       'STDs:vulvo-perineal condylomatosis', 'STDs:syphilis',
       'STDs:pelvic inflammatory disease', 'STDs:genital herpes',
       'STDs:molluscum contagiosum', 'STDs:AIDS', 'STDs:HIV',
       'STDs:Hepatitis B', 'STDs:HPV', 'STDs: Number of diagnosis',
       'STDs: Time since first diagnosis', 'STDs: Time since last diagnosis',
       'Dx:Cancer', 'Dx:CIN', 'Dx:HPV', 'Dx', 'Hinselmann', 'Schiller',
       'Citology', 'Biopsy'],
      dtype='object')

In [55]:
lungcancer = pd.read_json('lung_cancer.json')

In [56]:
lungcancer

,Name,Member_ID,Diagnosis,Age,Smokes,Smokes (years),Smokes (packs,AreaQ,Alkhol,family history,Result
0,Wick,91550,M,35,3,0,{'year)': '0'},5,4,0,1
1,Constantine,915664,M,27,20,0,{'year)': '0'},2,5,0,1
2,Anderson,915691,M,30,0,0,{'year)': '0'},5,2,0,0
3,Telles,915940,M,28,0,37,{'year)': '37'},8,1,1,0
4,Maradona,91594602,M,68,4,0,{'year)': '0'},5,6,0,1
...,...,...,...,...,...,...,...,...,...,...,...
1293,Borgnine,926424,M,26,13,0,{'year)': '0'},6,1,0,0
1294,Guinness,926682,B,77,20,0,{'year)': '0'},5,4,0,1
1295,Heston,926954,M,75,15,0,{'year)': '0'},3,5,0,1
1296,Peck,927241,M,43,30,7,{'year)': '1.6'},3,8,0,1
1297,Poitier,92751,B,51,25,0,{'year)': '0'},9,0,1,0

In [82]:
lungcancer.columns

Index(['Name', 'Member_ID', 'Diagnosis', 'Age', 'Smokes', 'Smokes (years)',
       'Smokes (packs', 'AreaQ', 'Alkhol', 'family history', 'Result'],
      dtype='object')

In [84]:
coviddeath = pd.read_json('covid.json')

In [86]:
coviddeath

,AFG,OWID_AFR,ALB,DZA,AND,AGO,AIA,ATG,ARG,ARM,...,UZB,VUT,VAT,VEN,VNM,WLF,OWID_WRL,YEM,ZMB,ZWE
continent,Asia,None,Europe,Africa,Europe,Africa,North America,North America,South America,Asia,...,Asia,Oceania,Europe,South America,Asia,Oceania,None,Asia,Africa,Africa
location,Afghanistan,Africa,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uzbekistan,Vanuatu,Vatican,Venezuela,Vietnam,Wallis and Futuna,World,Yemen,Zambia,Zimbabwe
last_updated_date,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,...,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-01,2021-11-05,2021-11-05,2021-11-05,2021-11-05
total_cases,156392.0,8526645.0,187994.0,206995.0,15618.0,64612.0,None,4078.0,5295260.0,316839.0,...,187381.0,6.0,27.0,411574.0,953547.0,None,249134481.0,9843.0,209852.0,133112.0
new_cases,29.0,9597.0,631.0,117.0,0.0,29.0,None,6.0,1271.0,1835.0,...,296.0,0.0,0.0,926.0,7504.0,None,516187.0,12.0,37.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
human_development_index,0.511,None,0.795,0.748,0.868,0.581,None,0.778,0.845,0.776,...,0.72,0.609,None,0.711,0.704,None,0.737,0.47,0.584,0.571
excess_mortality_cumulative_absolute,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
excess_mortality_cumulative,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
excess_mortality,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
excess_mortality_cumulative_per_million,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [87]:
coviddeath.columns

Index(['AFG', 'OWID_AFR', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ATG', 'ARG',
       'ARM',
       ...
       'UZB', 'VUT', 'VAT', 'VEN', 'VNM', 'WLF', 'OWID_WRL', 'YEM', 'ZMB',
       'ZWE'],
      dtype='object', length=225)