<a href="https://colab.research.google.com/github/malh718/datasci_1_loading/blob/main/HHA507HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HHA 507 HW 1

## HIV related CSV file examples

In [6]:
import pandas as pd

In [13]:
HIVny = pd.read_csv('HIVNY.csv')

In [14]:
HIVny

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
0,2011,All,All,All,All,All,3379,48.3,640,66,2366,33.8,1.1,71,2040,13.6,5.8,7.8
1,2011,All,All,Male,All,All,2595,79.1,480,66,1712,52.2,1.7,72,1423,13.4,5.7,7.7
2,2011,All,All,Female,All,All,733,21.1,153,66,622,17.6,0.6,68,605,14.0,6.0,8.0
3,2011,All,All,Transgender,All,All,51,99999.0,7,63,32,99999.0,99999.0,55,12,11.1,5.7,5.4
4,2011,All,All,Female,13 - 19,All,47,13.6,4,64,22,6.4,0.1,57,1,1.4,1.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000,2015,Staten Island,Willowbrook,Male,All,Asian/Pacific Islander,0,0.0,0,99999,0,0.0,0.1,100,0,0.0,99999.0,99999.0
6001,2015,Staten Island,Willowbrook,Male,All,Black,1,72.4,0,100,0,0.0,1.1,80,0,0.0,99999.0,99999.0
6002,2015,Staten Island,Willowbrook,Male,All,Latino/Hispanic,2,43.9,0,100,0,0.0,0.7,87,1,8.3,99999.0,99999.0
6003,2015,Staten Island,Willowbrook,Male,All,Other/Unknown,1,218.9,0,0,0,0.0,0.7,100,0,0.0,99999.0,99999.0
6004,2015,Staten Island,Willowbrook,Male,All,White,0,0.0,0,99999,0,0.0,0.2,93,0,0.0,99999.0,99999.0

In [15]:
HIVny.head(10)

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
0,2011,All,All,All,All,All,3379,48.3,640,66,2366,33.8,1.1,71,2040,13.6,5.8,7.8
1,2011,All,All,Male,All,All,2595,79.1,480,66,1712,52.2,1.7,72,1423,13.4,5.7,7.7
2,2011,All,All,Female,All,All,733,21.1,153,66,622,17.6,0.6,68,605,14.0,6.0,8.0
3,2011,All,All,Transgender,All,All,51,99999.0,7,63,32,99999.0,99999.0,55,12,11.1,5.7,5.4
4,2011,All,All,Female,13 - 19,All,47,13.6,4,64,22,6.4,0.1,57,1,1.4,1.4,0.0
5,2011,All,All,Female,20 - 29,All,178,24.7,20,67,96,13.3,0.3,48,19,7.2,3.2,4.0
6,2011,All,All,Female,30 - 39,All,176,26.9,31,66,133,20.3,0.6,61,53,9.4,5.7,3.7
7,2011,All,All,Female,40 - 49,All,195,33.0,50,62,210,35.5,1.4,66,184,15.9,7.8,8.1
8,2011,All,All,Female,50 - 59,All,130,23.5,32,72,133,24.0,1.3,73,231,24.1,11.5,12.6
9,2011,All,All,Female,60+,All,57,6.7,23,68,60,7.1,0.3,81,129,33.5,10.6,22.9

In [ ]:
HIVny.columns

Index(['Year', 'Borough', 'UHF', 'Gender', 'Age', 'Race', 'HIV diagnoses',
       'HIV diagnosis rate', 'Concurrent diagnoses',
       '% linked to care within 3 months', 'AIDS diagnoses',
       'AIDS diagnosis rate', 'PLWDHI prevalence', '% viral suppression',
       'Deaths', 'Death rate', 'HIV-related death rate',
       'Non-HIV-related death rate'],
      dtype='object')

This dataset is related to HIV in New York. The columns are broken into Year, Borough, Gender, Age, Race, HIV diagnosis and more.

In [16]:
HIVincidence = pd.read_csv('HIVIncidence Rate2009-2021.csv')

In [18]:
HIVincidence.head(10)

,Jurisdiction,Value,Race/ ethnicity,Year,Measure
0,Caroline,NaN,Asian,2017,HIV Incidence
1,State,20.4,All races/ ethnicities (aggregated),2017,HIV Incidence
2,Allegany,6.4,All races/ ethnicities (aggregated),2017,HIV Incidence
3,Anne Arundel,8.7,All races/ ethnicities (aggregated),2017,HIV Incidence
4,Baltimore City,44.7,All races/ ethnicities (aggregated),2017,HIV Incidence
5,Baltimore County,15.9,All races/ ethnicities (aggregated),2017,HIV Incidence
6,Calvert,6.5,All races/ ethnicities (aggregated),2017,HIV Incidence
7,Caroline,3.6,All races/ ethnicities (aggregated),2017,HIV Incidence
8,Carroll,5.6,All races/ ethnicities (aggregated),2017,HIV Incidence
9,Cecil,5.8,All races/ ethnicities (aggregated),2017,HIV Incidence

In [ ]:
HIVincidence

In [ ]:
HIVincidence.columns

Index(['Jurisdiction', 'Value', 'Race/ ethnicity', 'Year', 'Measure'], dtype='object')

This information was obstained from Maryland and shows specific cities and information in the colomns. Column information includes race, year and value.

In [19]:
STItest = pd.read_csv('STItest.csv')

In [21]:
STItest.head(10)

,Fiscal Years (FY),STI Test Type,Number of STI Tests Provided,Percentage of STI Tests Provided,Annotation Code,Annotation Description
0,2003,Chlamydia,"958,622",35%,NaN,NaN
1,2003,Genital Herpes,"4,965",0.18%,NaN,NaN
2,2003,Gonorrhea,"977,345",35%,NaN,NaN
3,2003,HIV,"404,956",14.65%,NaN,NaN
4,2003,Human Papillomavirus (HPV),"25,453",0.92%,NaN,NaN
5,2003,Other,"6,236",0.23%,NaN,NaN
6,2003,Syphilis,"387,412",14%,NaN,NaN
7,2004,Chlamydia,"978,408",35%,NaN,NaN
8,2004,Genital Herpes,"7,519",0.27%,NaN,NaN
9,2004,Gonorrhea,"969,806",35%,NaN,NaN

In [22]:
STItest.columns

Index(['Fiscal Years (FY)', 'STI Test Type ', 'Number of STI Tests Provided',
       'Percentage of STI Tests Provided', 'Annotation Code',
       'Annotation Description'],
      dtype='object')

This dataset is related to a program called Family PACT that has to do with STI testing. Colomns show the year, the test type and more information about the tests.

## Diabetes related XLSX file examples

In [11]:
import pandas as pd

In [23]:
diaindia = pd.read_excel('Diabetes.xlsx')

In [24]:
diaindia.head(10)

,States/UTs,Area,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Men age 15-49 years who are anaemic (<13.0 g/dl)22 (%),Men age 15-19 years who are anaemic (<13.0 g/dl)22 (%),Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%),Men (age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)
0,India,Urban,160138,179535,26420,20.39,25.04,,7.97,16.27,7.81,8.54,17.85
1,India,Rural,476561,544580,75419,27.41,33.86,5.87,5.47,12.27,7.02,6.49,14.51
2,India,Total,636699,724115,101839,25.04,31.13,6.12,6.25,13.51,7.27,7.15,15.58
3,Andaman & Nicobar Islands,Urban,527,557,85,9.18,*,8.59,9.39,19.64,9.49,8.56,19.44
4,Andaman & Nicobar Islands,Rural,2097,1840,282,20.36,-25.59,6.7,7.32,16.19,9.12,6.55,17.12
5,Andaman & Nicobar Islands,Total,2624,2397,367,16.06,-27.09,7.41,8.09,17.47,9.25,7.26,17.93
6,Andhra Pradesh,Urban,3192,3161,433,13.79,12.78,7.81,13.24,23.24,9.15,13.68,24.88
7,Andhra Pradesh,Rural,8154,7814,1125,17.32,21.35,7.02,9.23,17.90,8.13,10.43,20.49
8,Andhra Pradesh,Total,11346,10975,1558,16.2,18.67,7.26,10.43,19.50,8.43,11.40,21.81
9,Arunachal Pradesh,Urban,3714,4211,621,21.41,21.94,4.73,3.66,9.56,6.35,4.64,12.03

In [ ]:
diaindia.columns

Index(['States/UTs', 'Area', 'Number of Households surveyed',
       'Number of Women age 15-49 years interviewed',
       'Number of Men age 15-54 years interviewed',
       'Men age 15-49 years who are anaemic (<13.0 g/dl)22 (%)',
       'Men age 15-19 years who are anaemic (<13.0 g/dl)22 (%)',
       'Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)',
       'Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)',
       'Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)',
       'Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)',
       'Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)',
       'Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)'],
      dtype='object')

This dataset is related to men and woman in India who have diabetes. The columns refer to characteristics of participants and their specific de-identified data.

In [26]:
gestationaldiabetes = pd.read_excel('Gestdia.xlsx')

In [27]:
gestationaldiabetes.head(10)

,Case Number,Age,No of Pregnancy,Gestation in previous Pregnancy,BMI,HDL,Family History,unexplained prenetal loss,Large Child or Birth Default,PCOS,Sys BP,Dia BP,OGTT,Hemoglobin,Sedentary Lifestyle,Prediabetes,Class Label(GDM /Non GDM)
0,1,22,2,1,NaN,55.0,0,0,0,0,102.0,69,NaN,12.0,0,0,0
1,2,26,2,1,NaN,53.0,0,0,0,0,101.0,63,NaN,12.4,0,0,0
2,3,29,1,0,NaN,50.0,0,0,0,0,118.0,79,NaN,14.3,0,0,0
3,4,28,2,1,NaN,51.0,0,0,0,0,99.0,70,NaN,15.0,0,0,0
4,5,21,2,1,NaN,52.0,0,0,0,0,116.0,65,NaN,15.0,0,0,0
5,6,29,2,1,NaN,51.0,0,0,0,0,98.0,63,NaN,15.2,0,0,0
6,7,26,2,1,NaN,51.0,0,0,0,0,94.0,68,NaN,15.0,0,0,0
7,8,27,1,0,NaN,52.0,0,0,0,0,116.0,63,NaN,12.0,0,0,0
8,9,26,1,0,NaN,57.0,0,0,0,0,108.0,62,NaN,14.0,0,0,0
9,10,21,2,1,NaN,52.0,0,0,0,0,98.0,78,NaN,13.0,0,0,0

In [ ]:
gestationaldiabetes.columns

Index(['Case Number', 'Age', 'No of Pregnancy',
       'Gestation in previous Pregnancy', 'BMI', 'HDL', 'Family History',
       'unexplained prenetal loss', 'Large Child or Birth Default', 'PCOS',
       'Sys BP', 'Dia BP', 'OGTT', 'Hemoglobin', 'Sedentary Lifestyle',
       'Prediabetes', 'Class Label(GDM /Non GDM)'],
      dtype='object')

This dataset refers to a number of cases where pregnancies had gestational diabetes as well as other information such as hemoglobin and lifestyle choices.

In [28]:
diabetespregstats = pd.read_excel('diapregstats.xlsx')

In [29]:
diabetespregstats.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [ ]:
diabetespregstats.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

This dataset has to do with gestational diabetes. The colomns contain information about a case such as insulin,bmi and more.

## Cancer and COVID related JSON file examples

In [ ]:
import pandas as pd

In [32]:
cervcanc = pd.read_json('cerv_cancer.json')

In [33]:
cervcanc.head(10)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs,Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4,15,1,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
1,15,1,14,1,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
2,34,1,?,1,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
3,52,5,16,4,1,37,{'year)': '37'},1,3,0,...,?,?,1,0,1,0,0,0,0,0
4,46,3,21,4,0,0,{'year)': '0'},1,15,0,...,?,?,0,0,0,0,0,0,0,0
5,42,3,23,2,0,0,{'year)': '0'},0,0,0,...,?,?,0,0,0,0,0,0,0,0
6,51,3,17,6,1,34,{'year)': '3.4'},0,0,1,...,?,?,0,0,0,0,1,1,0,1
7,26,1,26,3,0,0,{'year)': '0'},1,2,1,...,?,?,0,0,0,0,0,0,0,0
8,45,1,20,5,0,0,{'year)': '0'},0,0,0,...,?,?,1,0,1,1,0,0,0,0
9,44,3,15,?,1,1.266972909,{'year)': '2.8'},0,0,?,...,?,?,0,0,0,0,0,0,0,0

In [ ]:
cervcanc.columns

Index(['Age', 'Number of sexual partners', 'First sexual intercourse',
       'Num of pregnancies', 'Smokes', 'Smokes (years)', 'Smokes (packs',
       'Hormonal Contraceptives', 'Hormonal Contraceptives (years)', 'IUD',
       'IUD (years)', 'STDs', 'STDs (number)', 'STDs:condylomatosis',
       'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis',
       'STDs:vulvo-perineal condylomatosis', 'STDs:syphilis',
       'STDs:pelvic inflammatory disease', 'STDs:genital herpes',
       'STDs:molluscum contagiosum', 'STDs:AIDS', 'STDs:HIV',
       'STDs:Hepatitis B', 'STDs:HPV', 'STDs: Number of diagnosis',
       'STDs: Time since first diagnosis', 'STDs: Time since last diagnosis',
       'Dx:Cancer', 'Dx:CIN', 'Dx:HPV', 'Dx', 'Hinselmann', 'Schiller',
       'Citology', 'Biopsy'],
      dtype='object')

This dataset pertains to cervical cancer of specific patients. The colomns show information pertaining to age, sexual history and STD testing.

In [34]:
lungcancer = pd.read_json('lung_cancer.json')

In [36]:
lungcancer.head(10)

,Name,Member_ID,Diagnosis,Age,Smokes,Smokes (years),Smokes (packs,AreaQ,Alkhol,family history,Result
0,Wick,91550,M,35,3,0,{'year)': '0'},5,4,0,1
1,Constantine,915664,M,27,20,0,{'year)': '0'},2,5,0,1
2,Anderson,915691,M,30,0,0,{'year)': '0'},5,2,0,0
3,Telles,915940,M,28,0,37,{'year)': '37'},8,1,1,0
4,Maradona,91594602,M,68,4,0,{'year)': '0'},5,6,0,1
5,Ronaldo,916221,M,34,0,0,{'year)': '0'},10,0,0,0
6,Tal,916799,M,58,15,34,{'year)': '3.4'},10,0,0,0
7,Bates,916838,M,22,12,0,{'year)': '0'},5,2,1,0
8,Kidman,917062,M,45,2,0,{'year)': '0'},6,0,1,0
9,Milland,917080,M,52,18,1.266972909,{'year)': '2.8'},4,5,0,1

In [ ]:
lungcancer.columns

Index(['Name', 'Member_ID', 'Diagnosis', 'Age', 'Smokes', 'Smokes (years)',
       'Smokes (packs', 'AreaQ', 'Alkhol', 'family history', 'Result'],
      dtype='object')

This dataset contains information about lungcancer and smoking history. The colomns are related to smoking history such as years, family who have smoked etc.

In [37]:
coviddeath = pd.read_json('covid.json')

In [39]:
coviddeath.head(10)

,AFG,OWID_AFR,ALB,DZA,AND,AGO,AIA,ATG,ARG,ARM,...,UZB,VUT,VAT,VEN,VNM,WLF,OWID_WRL,YEM,ZMB,ZWE
continent,Asia,None,Europe,Africa,Europe,Africa,North America,North America,South America,Asia,...,Asia,Oceania,Europe,South America,Asia,Oceania,None,Asia,Africa,Africa
location,Afghanistan,Africa,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uzbekistan,Vanuatu,Vatican,Venezuela,Vietnam,Wallis and Futuna,World,Yemen,Zambia,Zimbabwe
last_updated_date,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,...,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-05,2021-11-01,2021-11-05,2021-11-05,2021-11-05,2021-11-05
total_cases,156392.0,8526645.0,187994.0,206995.0,15618.0,64612.0,None,4078.0,5295260.0,316839.0,...,187381.0,6.0,27.0,411574.0,953547.0,None,249134481.0,9843.0,209852.0,133112.0
new_cases,29.0,9597.0,631.0,117.0,0.0,29.0,None,6.0,1271.0,1835.0,...,296.0,0.0,0.0,926.0,7504.0,None,516187.0,12.0,37.0,0.0
new_cases_smoothed,28.0,4754.429,522.0,103.571,14.571,44.429,None,5.429,1116.143,1756.143,...,298.0,0.0,0.0,1026.714,6167.286,None,443711.857,10.0,21.429,26.571
total_deaths,7284.0,219201.0,2948.0,5939.0,130.0,1719.0,None,104.0,116083.0,6582.0,...,1334.0,1.0,None,4946.0,22412.0,None,5038372.0,1905.0,3662.0,4685.0
new_deaths,0.0,236.0,4.0,3.0,0.0,1.0,None,0.0,28.0,50.0,...,2.0,0.0,None,10.0,70.0,None,8837.0,4.0,0.0,0.0
new_deaths_smoothed,2.143,173.429,5.571,3.714,0.0,1.714,None,0.286,21.143,50.0,...,2.286,0.0,0.0,12.286,63.714,None,6945.0,4.0,0.286,1.429
total_cases_per_million,3925.953,6208.03,65436.24,4639.414,201902.94,1904.071,None,41305.405,116109.296,106747.081,...,5521.638,19.08,33251.232,14338.086,9713.338,None,31636.262,322.82,11091.158,8819.937

In [ ]:
coviddeath.columns

Index(['AFG', 'OWID_AFR', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ATG', 'ARG',
       'ARM',
       ...
       'UZB', 'VUT', 'VAT', 'VEN', 'VNM', 'WLF', 'OWID_WRL', 'YEM', 'ZMB',
       'ZWE'],
      dtype='object', length=225)

This dataset refers to covid deaths globally. Information present in this dataset includes location, date of new cases and mortality related information.